# Generated by Django 3.2.13 on 2022-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('emp_id',),
            },
        ),
    ]
